---
kind: Template
apiVersion: v1
metadata:
  name: golang-demo
labels:
  template: golang-demo
  app: golang-demo
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: golang-demo-service
  spec:
    ports:
    - name: http-web
      port: 8080
      targetPort: 8080
    selector:
      name: golang-demo  
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: golang-demo-imagestream
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: golang-demo-v1-0
  spec:
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      contextDir: "${CONTEXT_DIR}"
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: golang-demo-imagestream:1.0
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: "${GITHUB_WEBHOOK_SECRET}"
    postCommit:
      script: go test -v ./...
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: golang-demo-v1-1
  spec:
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL_1_1}"
        ref: "${SOURCE_REPOSITORY_REF_1_1}"
      contextDir: "${CONTEXT_DIR}"
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: golang-demo-imagestream:1.1
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: "${GITHUB_WEBHOOK_SECRET}"
    postCommit:
      script: go test -v ./...
- kind: HorizontalPodAutoscaler
  apiVersion: autoscaling/v1
  metadata:
    name: golang-demo-hpa
  spec:
    maxReplicas: 10
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: golang-demo-v1-0
    targetCPUUtilizationPercentage: 30
parameters:
- name: SOURCE_REPOSITORY_URL
  value: https://github.com/tuanbo91/golang-ex.git
- name: SOURCE_REPOSITORY_REF
  value: v1.0
- name: SOURCE_REPOSITORY_URL_1_1
  value: https://github.com/tuanbo91/golang-ex.git
- name: SOURCE_REPOSITORY_REF_1_1
  value: v1.1
- name: CONTEXT_DIR
- name: GITHUB_WEBHOOK_SECRET
  generate: expression
  from: "[a-zA-Z0-9]{40}"
